config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :likes, only: [:create, :destroy], module: 'posts'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user

  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type] }

  after_create :update_likes_count
  after_destroy :update_likes_count

  private

  def update_likes_count
    likeable.update_column(:likes_count, likeable.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, as: :likeable, dependent: :destroy
  has_many :liking_users, through: :likes, source: :user

  default_scope { order(created_at: :desc) }

  validates :title, presence: true
  validates :content, presence: true, length: { maximum: 160 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  has_many :posts, dependent: :destroy
  has_many :likes

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.includes(:user)
    @likes = current_user.likes.where(likeable_type: "Post").index_by(&:likeable_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_likeable

  def create
    @likeable.likes.create(user: current_user)
    redirect_to root_path, notice: 'Item liked!'
  end

  def destroy
    @likeable.likes.find_by(user: current_user).destroy
    redirect_to root_path, notice: 'Item unliked!'
  end
end

app/controllers/posts/likes_controller.rb
class Posts::LikesController < LikesController
  private

  def set_likeable
    @likeable = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = current_user.posts.includes(:user)
    @likes = current_user.likes.where(likeable_type: "Post").index_by(&:likeable_id)
  end

  def show; end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      flash.now[:alert] = @post.errors.full_messages
      render :new
    end
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Post was successfully deleted.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= render partial: 'posts/posts', locals: { heading: 'All Posts', posts: @posts, likes: @likes } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/shared/navbar' %>
    <div class="container-fluid">
      <%= render 'layouts/shared/flash' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice]  %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="alert alert-danger mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Simple Blog", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My Posts", posts_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary" %>
          </li>
          <li class="nav-item">
            <%= link_to "Signup", new_user_registration_path, class: "btn btn-outline-secondary ms-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control', rows: 5, maxlength: 160, oninput: "updateCharCount()" %>
    <small id="charCount" class="form-text text-muted">0/160 characters used</small>
  </div>

  <div class="mt-2 form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>

  <script>
    function updateCharCount() {
      const contentField = document.querySelector('textarea');
      const charCount = document.getElementById('charCount');
      const currentLength = contentField.value.length;
      charCount.textContent = `${currentLength}/160 characters used`;
    }

    // Initialize the character count on page load
    document.addEventListener("DOMContentLoaded", function() {
      updateCharCount();
    });
  </script>
<% end %>

app/views/posts/_posts.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h1><%= heading %></h1>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary ml-auto' %>
</div>

<div class="row">
  <% posts.each do |post| %>
    <div class="col-md-8 offset-md-2 mb-4">
      <div class="card shadow-sm">
        <div class="card-body">
          <div class="d-flex align-items-center mb-3">
            <%= image_tag 'user.jpg', alt: post.user.full_name, class: 'rounded-circle mr-3', style: 'width: 50px; height: 50px;' %>
            <div>
              <h5 class="card-title mb-1"><%= post.user.full_name %></h5>
              <small class="text-muted"><%= time_ago_in_words(post.created_at) %> ago</small>
            </div>
          </div>
          <p class="card-text"><%= post.content %></p>

          <div class="d-flex justify-content-between align-items-center">
            <div>
              <% if likes[post.id].present? %>
                <% like = likes[post.id] %>
                <%= button_to post_like_path(post, like), method: :delete, remote: true, class: 'btn btn-sm btn-link text-primary', data: { turbo_frame: "post_#{post.id}" } do %>
                  <%= image_tag 'like-filled.png', class: 'rounded-circle mr-3', style: 'width: 20px; height: 20px;' %>
                  ( <%= post.likes_count %> )
                <% end %>
              <% else %>
                <%= button_to post_likes_path(post), remote: true, class: 'btn btn-sm btn-link text-muted', data: { turbo_frame: "post_#{post.id}" } do %>
                  <%= image_tag 'like-unfilled.png', class: 'rounded-circle mr-3', style: 'width: 20px; height: 20px;' %>
                  ( <%= post.likes_count %> )
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', :back, class: 'btn btn-light' %>

app/views/posts/index.html.erb
<%= render partial: 'posts', locals: { heading: 'My Posts', posts: @posts, likes: @likes } %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', :back, class: 'btn btn-light' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<p><%= @post.content %></p>

<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-secondary' %>
<%= link_to 'Back', posts_path, class: 'btn btn-light' %>